- name: Installing Putty Client MSI 
  hosts: all
 
  tasks:    
      - name: Create a mapped drive that requires authentication
        win_mapped_drive:
          letter: T
          path: \\ansiblestg001.file.core.windows.net/tools
          state: present
          
      - name: Copy my Installer	
        win_copy:	
          src: T:\putty-64bit-0.74-installer.msi	
          dest: C:\ansible_tools\putty-64bit-0.74-installer.msi
       


      - name: Install MSI
        win_package: 
          path: C:\ansible_tools\putty-64bit-0.74-installer.msi
          state: present
