- name: Installing Putty Client MSI 
  hosts: all
  name: "Installing Putty Client MSI"
  tasks: 
    - 
      name: "Create a mapped drive that requires authentication"
      vars: 
        ansible_become: true
        ansible_become_method: runas
        ansible_become_pass: "{{ ansiblestg_password }}"
        ansible_become_user: "{{ ansiblestg_user }}"
      win_mapped_drive: 
        letter: T
        path: \\ansiblestg001.file.core.windows.net\tools
        state: present
    - 
      name: "Copy my Installer"
      win_copy: 
        dest: "C:\\ansible_tools\\putty-64bit-0.74-installer.msi"
        src: "T:\\putty-64bit-0.74-installer.msi"
    - 
      name: "Install MSI"
      win_package: 
        path: "C:\\ansible_tools\\putty-64bit-0.74-installer.msi"
        state: present
