- name: Installing Putty Client MSI 
  hosts: all
 
  tasks:    
      - name: Create a mapped drive that requires authentication
         win_mapped_drive:
          letter: M
          path: \\SERVER\C$
          state: present


      - name: Install MSI
        win_package: 
          path: C:\ansible_tools\putty-64bit-0.74-installer.msi
          state: present
