- name: Installing Putty Client MSI 
  hosts: all
  name: "Installing Putty Client MSI"
  tasks: 
    - 
      name: "Create a mapped drive that requires authentication"
      win_mapped_drive: 
        letter: T
        path: \\ansiblestg001.file.core.windows.net\tools
        state: present
        username: '{{ ansiblestg_user }}'
        password: '{{ ansiblestg_password }}'

