- name: Installing Putty Client MSI 
  hosts: all
  tasks: 
    -
      name: Create directory structure
      win_file:
        path: "C:\\ansible_tools"
        state: directory
    - 
      name: "Copy my Installer"
      win_copy: 
        dest: "C:\\ansible_tools\\putty-64bit-0.74-installer.msi"
        src: /opt/tools/putty-64bit-0.74-installer.msi
    - 
      name: "Install MSI"
      win_package: 
        path: "C:\\ansible_tools\\putty-64bit-0.74-installer.msi"
        state: present
#    - 
#      name: Install all critical and security updates
#      win_updates:
#        category_names:
#        - CriticalUpdates
#        - SecurityUpdates
#        state: installed
#      register: update_result
      
      
- name: Installing 7ZIP MSI 
  hosts: ansiblehostwin001
  tasks: 
    -
      name: "Copy my Installer"
      win_copy: 
        dest: "C:\\ansible_tools\\7z1900-X64.msi"
        src: /opt/tools/7z1900-X64.msi
    - 
      name: "Install MSI"
      win_package: 
        path: "C:\\ansible_tools\\7z1900-X64.msi"
        state: present

- name: Installing VLC MSI 
  hosts: ansiblehostwin002
  tasks: 
    -
      name: "Copy my Installer"
      win_copy: 
        dest: "C:\\ansible_tools\\Video_Lan_VLC_Media_Player_3.0.5_P1.0.msi"
        src: /opt/tools/Video_Lan_VLC_Media_Player_3.0.5_P1.0.msi
    - 
      name: "Install MSI"
      win_package: 
        path: "C:\\ansible_tools\\Video_Lan_VLC_Media_Player_3.0.5_P1.0.msi"
        state: present
